export const GET_MY_FORMS = 'GET_MY_FORMS';
export const GET_FORM_BY_CODE = 'GET_FORM_BY_CODE';
export const UPDATE_FORM_BY_CODE = 'UPDATE_FORM_BY_CODE';
export const SEND_ANSWER_TO_FORM_BY_CODE = 'SEND_ANSWER_TO_FORM_BY_CODE';
export const GET_PARTICIPANTS_FORM_BY_CODE = 'GET_PARTICIPANTS_FORM_BY_CODE';
export const GET_AVERAGE_FORM_RESPONSES = 'GET_AVERAGE_FORM_RESPONSES';